version: '3.0'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_MAXACTIVE=60
      - SONARQUBE_JDBC_MAXIDLE=5
      - SONARQUBE_JDBC_MINIDLE=1
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    depends_on:
      - db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  db:
    image: postgres:latest
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - sonarnet
    volumes:
      - sonarqube_db:/var/lib/postgresql/data

  jfrog:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: jfrog
    ports:
      - "8082:8082"
      - "8081:8081"
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db:
  artifactory-data:
